version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DEBUG=True
      - ALLOWED_HOST=*
      - SECRET_KEY=qWxPJrZCLeHZraNTWjEKHdJJxJyho8
      - SEND_SUSPICIOUS_BEHAVIOR_WARNINGS=False
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - FROM_EMAIL= <from email>
      - EMAIL_HOST= <host>
      - EMAIL_PORT= <port>
      - EMAIL_USER= <email user>
      - EMAIL_PASSWORD= <password>
      - EMAIL_USE_TLS=True
      - SITE_URL= <site url>
      - CORS_ORIGIN_WHITELIST= <origin white list>
    ports:
      - "8006:8000"
    depends_on:
      - db
    volumes:
      - ./media:/app/media
