---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pleio-account
  namespace: gctoolsv2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pleio-account
    spec:
      containers:
      - name: pleio-account
        image: gctools-outilsgc/pleio_account:1.0.0
        ports:
        - containerPort: 8000
        env:
        - name: "DEBUG"
          value: "True"
        - name: "ALLOWED_HOST"
          value: "*"
        - name: "SECRET_KEY"
          value: "qWxPJrZCLeHZraNTWjEKHdJJxJyho8"
        - name: "DB_HOST"
          value: "localhost"
        - name: "DB_USER"
          value: "postgres"
        - name: "DB_PASSWORD"
          value: "postgres"
      - name: pleio-account-database
        image: postgres
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pleio-account
  namespace: gctoolsv2
  labels:
    name: pleio-account
  annotations:
    VIRTUAL_HOST: "gcidentity.lpss.me"
    VIRTUAL_PORT: "8000"
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: pleio-account
